_BASE_: "coco_additional/faster_rcnn_R_50_FPN_focal_cross_coco_unsupW2.yaml"
MODEL:
  WEIGHTS: ""
  ROI_HEADS:
    NUM_CLASSES: 9
SOLVER:
  IMS_PER_BATCH: 2
  IMG_PER_BATCH_LABEL: 1
  IMG_PER_BATCH_UNLABEL: 1
  BASE_LR: 0.01
  MAX_ITER: 360000
  STEPS: (3000, 6000, 10000)
  FACTOR_LIST: (1, 1, 1, 1)
DATALOADER:
  NUM_WORKERS: 2
DATASETS:
  CROSS_DATASET: True
  TRAIN_LABEL: ("oct_ss_train",)
  TRAIN_UNLABEL: ("oct_ss_train_unlabel",)
  TEST: ("oct_ss_test",)
SEMISUPNET:
  Trainer: "cdpl"
  CDPL_ENABLED: True
  CDPL_TAU_BASE: 0.5
  CDPL_ALPHA_TAIL: 0.15
  CDPL_MIN_CLS_THRESHOLD: 0.35
  DEBUG_PSEUDO_STATS: True
  BBOX_THRESHOLD: 0.5
  BURN_UP_STEP: 90000
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 2.0
TEST:
  EVAL_PERIOD: 1000
